#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source ${SCRIPT_DIR}/scripts/prereq.sh

export PYTHONPATH=${SCRIPT_DIR}/inspector-pkg/src:${SCRIPT_DIR}/installer-pkg/src:${SCRIPT_DIR}/dump-pkg/src
#
# Expected script args are the installed python module name followed by the program arguments.
#
# Example:
#   ~ run dump -m=debug
#
python3 -m $@
