
clean:
	rm -rf build
	rm -rf dist
	rm -rf src/*.egg-info

test:
	python3 setup.py test

install:
	pip3 install --user .

ciinstall:
	pip3 install .

uninstall:
	pip3 uninstall -y workstation-inspector-sha1n